<?php
require('lib/auth.php');
require('lib/config.php');
require('lib/datetime.php');
require('lib/layout.php');
require('lib/mysql.php');
require('lib/perm.php');
require('lib/post.php');
require('lib/thread.php');
require('lib/user.php');
?>