<?php

$rankset_data['Mario'] = array(
	array('p' => 0, 'str' => 'Non-poster'),
	array('p' => 1, 'str' => 'Newcomer'),
	array('p' => 10, 'str' => '<img src="img/ranks/microgoomba.gif"><br>Micro-Goomba'),
	array('p' => 20, 'str' => '<img src=img/ranks/goomba.gif><br>Goomba'),
	array('p' => 35, 'str' => '<img src=img/ranks/redgoomba.gif><br>Red Goomba'),
	array('p' => 50, 'str' => '<img src=img/ranks/redparagoomba.gif><br>Red Paragoomba'),
	array('p' => 65, 'str' => '<img src=img/ranks/paragoomba.gif><br>Paragoomba'),
	array('p' => 80, 'str' => '<img src=img/ranks/shyguy.gif><br>Shyguy'),
	array('p' => 100, 'str' => '<img src=img/ranks/koopa.gif><br>Koopa'),
	array('p' => 120, 'str' => '<img src=img/ranks/redkoopa.gif><br>Red Koopa'),
	array('p' => 140, 'str' => '<img src=img/ranks/paratroopa.gif><br>Paratroopa'),
	array('p' => 160, 'str' => '<img src=img/ranks/redparatroopa.gif><br>Red Paratroopa'),
	array('p' => 180, 'str' => '<img src=img/ranks/cheepcheep.gif><br>Cheep-cheep'),
	array('p' => 200, 'str' => '<img src=img/ranks/redcheepcheep.gif><br>Red Cheep-cheep'),
	array('p' => 225, 'str' => '<img src=img/ranks/ninji.gif><br>Ninji'),
	array('p' => 250, 'str' => '<img src=img/ranks/flurry.gif><br>Flurry'),
	array('p' => 275, 'str' => '<img src=img/ranks/snifit.gif><br>Snifit'),
	array('p' => 300, 'str' => '<img src=img/ranks/porcupo.gif><br>Porcupo'),
	array('p' => 325, 'str' => '<img src=img/ranks/panser.gif><br>Panser'),
	array('p' => 350, 'str' => '<img src=img/ranks/mole.gif><br>Mole'),
	array('p' => 375, 'str' => '<img src=img/ranks/beetle.gif><br>Buzzy Beetle'),
	array('p' => 400, 'str' => '<img src=img/ranks/nipperplant.gif><br>Nipper Plant'),
	array('p' => 425, 'str' => '<img src=img/ranks/bloober.gif><br>Bloober'),
	array('p' => 450, 'str' => '<img src=img/ranks/busterbeetle.gif><br>Buster Beetle'),
	array('p' => 475, 'str' => '<img src=img/ranks/beezo.gif><br>Beezo'),
	array('p' => 500, 'str' => '<img src=img/ranks/bulletbill.gif><br>Bullet Bill'),
	array('p' => 525, 'str' => '<img src=img/ranks/rex.gif><br>Rex'),
	array('p' => 550, 'str' => '<img src=img/ranks/lakitu.gif><br>Lakitu'),
	array('p' => 575, 'str' => '<img src=img/ranks/spiny.gif><br>Spiny'),
	array('p' => 600, 'str' => '<img src=img/ranks/bobomb.gif><br>Bob-Omb'),
	array('p' => 625, 'str' => '<img src=img/ranks/drybones.gif><br>Dry Bones'),
	array('p' => 650, 'str' => '<img src=img/ranks/cobrat.gif><br>Cobrat'),
	array('p' => 675, 'str' => '<img src=img/ranks/pokey.gif><br>Pokey'),
	array('p' => 700, 'str' => '<img src=img/ranks/spike.gif><br>Spike'),
	array('p' => 725, 'str' => '<img src=img/ranks/hedgehog.gif><br>Melon Bug'),
	array('p' => 750, 'str' => '<img src=img/ranks/lanternghost.gif><br>Lantern Ghost'),
	array('p' => 775, 'str' => '<img src=img/ranks/fuzzy.gif><br>Fuzzy'),
	array('p' => 800, 'str' => '<img src=img/ranks/bandit.gif><br>Bandit'),
	array('p' => 830, 'str' => '<img src=img/ranks/superkoopa.gif><br>Super Koopa'),
	array('p' => 860, 'str' => '<img src=img/ranks/redsuperkoopa.gif><br>Red Super Koopa'),
	array('p' => 900, 'str' => '<img src=img/ranks/boo.gif><br>Boo'),
	array('p' => 925, 'str' => '<img src=img/ranks/boo2.gif><br>Boo'),
	array('p' => 950, 'str' => '<img src=img/ranks/fuzzball.gif><br>Fuzz Ball'),
	array('p' => 1000, 'str' => '<img src=img/ranks/boomerangbrother.gif><br>Boomerang Brother'),
	array('p' => 1050, 'str' => '<img src=img/ranks/hammerbrother.gif><br>Hammer Brother'),
	array('p' => 1100, 'str' => '<img src=img/ranks/firebrother.gif><br>Fire Brother'),
	array('p' => 1150, 'str' => '<img src=img/ranks/firesnake.gif><br>Fire Snake'),
	array('p' => 1200, 'str' => '<img src=img/ranks/giantgoomba.gif><br>Giant Goomba'),
	array('p' => 1250, 'str' => '<img src=img/ranks/giantkoopa.gif><br>Giant Koopa'),
	array('p' => 1300, 'str' => '<img src=img/ranks/giantredkoopa.gif><br>Giant Red Koopa'),
	array('p' => 1350, 'str' => '<img src=img/ranks/giantparatroopa.gif><br>Giant Paratroopa'),
	array('p' => 1400, 'str' => '<img src=img/ranks/giantredparatroopa.gif><br>Giant Red Paratroopa'),
	array('p' => 1450, 'str' => '<img src=img/ranks/chuck.gif><br>Chuck'),
	array('p' => 1500, 'str' => '<img src=img/ranks/thwomp.gif><br>Thwomp'),
	array('p' => 1550, 'str' => '<img src=img/ranks/bigcheepcheep.gif><br>Boss Bass'),
	array('p' => 1600, 'str' => '<img src=img/ranks/volcanolotus.gif><br>Volcano Lotus'),
	array('p' => 1650, 'str' => '<img src=img/ranks/lavalotus.gif><br>Lava Lotus'),
	array('p' => 1700, 'str' => '<img src=img/ranks/ptooie2.gif><br>Ptooie'),
	array('p' => 1800, 'str' => '<img src=img/ranks/sledgebrother.gif><br>Sledge Brother'),
	array('p' => 1900, 'str' => '<img src=img/ranks/boomboom.gif><br>Boomboom'),
	array('p' => 2000, 'str' => '<img src=img/ranks/birdopink.gif><br>Birdo'),
	array('p' => 2100, 'str' => '<img src=img/ranks/birdored.gif><br>Red Birdo'),
	array('p' => 2200, 'str' => '<img src=img/ranks/birdogreen.gif><br>Green Birdo'),
	array('p' => 2300, 'str' => '<img src=img/ranks/iggy.gif><br>Larry Koopa'),
	array('p' => 2400, 'str' => '<img src=img/ranks/morton.gif><br>Morton Koopa'),
	array('p' => 2500, 'str' => '<img src=img/ranks/wendy.gif><br>Wendy Koopa'),
	array('p' => 2600, 'str' => '<img src=img/ranks/larry.gif><br>Iggy Koopa'),
	array('p' => 2700, 'str' => '<img src=img/ranks/roy.gif><br>Roy Koopa'),
	array('p' => 2800, 'str' => '<img src=img/ranks/lemmy.gif><br>Lemmy Koopa'),
	array('p' => 2900, 'str' => '<img src=img/ranks/ludwig.gif><br>Ludwig Von Koopa'),
	array('p' => 3000, 'str' => '<img src=img/ranks/triclyde.gif><br>Triclyde'),
	array('p' => 3100, 'str' => '<img src=img/ranks/kamek.gif><br>Magikoopa'),
	array('p' => 3200, 'str' => '<img src=img/ranks/wart.gif><br>Wart'),
	array('p' => 3300, 'str' => '<img src=img/ranks/babybowser.gif><br>Baby Bowser'),
	array('p' => 3400, 'str' => '<img src=img/ranks/bowser.gif><br>King Bowser Koopa'),
	array('p' => 3500, 'str' => '<img src=img/ranks/yoshi.gif><br>Yoshi'),
	array('p' => 3600, 'str' => '<img src=img/ranks/yoshiyellow.gif><br>Yellow Yoshi'),
	array('p' => 3700, 'str' => '<img src=img/ranks/yoshiblue.gif><br>Blue Yoshi'),
	array('p' => 3800, 'str' => '<img src=img/ranks/yoshired.gif><br>Red Yoshi'),
	array('p' => 3900, 'str' => '<img src=img/ranks/kingyoshi.gif><br>King Yoshi'),
	array('p' => 4000, 'str' => '<img src=img/ranks/babymario.gif><br>Baby Mario'),
	array('p' => 4100, 'str' => '<img src=img/ranks/luigismall.gif><br>Luigi'),
	array('p' => 4200, 'str' => '<img src=img/ranks/mariosmall.gif><br>Mario'),
	array('p' => 4300, 'str' => '<img src=img/ranks/luigibig.gif><br>Super Luigi'),
	array('p' => 4400, 'str' => '<img src=img/ranks/mariobig.gif><br>Super Mario'),
	array('p' => 4500, 'str' => '<img src=img/ranks/luigifire.gif><br>Fire Luigi'),
	array('p' => 4600, 'str' => '<img src=img/ranks/mariofire.gif><br>Fire Mario'),
	array('p' => 4700, 'str' => '<img src=img/ranks/luigicape.gif><br>Cape Luigi'),
	array('p' => 4800, 'str' => '<img src=img/ranks/mariocape.gif><br>Cape Mario'),
	array('p' => 4900, 'str' => '<img src=img/ranks/luigistar.gif><br>Star Luigi'),
	array('p' => 5000, 'str' => '<img src=img/ranks/mariostar.gif><br>Star Mario')
);

?>